services:
  - type: web
    name: nombre-de-tu-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Reservas.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nombreProyecto.settings
      - key: SECRET_KEY
        value: tu_clave_secreta
      - key: DEBUG
        value: False
