# Generated by Django 5.2 on 2025-07-26 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('edad_aproximada', models.IntegerField()),
                ('fecha_rescate', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animales/')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoLiberacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_liberacion', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='eventos/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.animal')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.reservanatural')),
            ],
        ),
    ]
